### ISSUE TITLE
[Program]: Write a PHP program to print number to words in indian numbering system

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1051]
### Description

Write a PHP program to print number to words in indian numbering system
```
Input  : 123456789
Output : Twelve Crore Thirty Four Lakh Fifty Six Thousand Seven Hundred Eighty Nine
```
<details>
<summary>How to contribute</summary>

- Save the solution in `print_number_to_words_in_indian_numbering_system.php` file
- Add `print_number_to_words_in_indian_numbering_system.php` file in `print-number-to-words-in-indian-numbering-system` folder

</details>

**Comment by larsjarred9** [comment]
Hey there @harshraj8843 I would like to take on this issue, going to be building it in the next 48 hours. Thanks for your helpful issue :)

**Comment by larsjarred9** [comment]
!assign Hey there @harshraj8843 I would like to take on this issue, going to be building it in the next 48 hours. Thanks for your helpful issue :)
