### ISSUE TITLE
[Program]: Write a R program to calculate compound interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1074]
### Description

Write a R program to calculate compound interest

Compound interest = principal amount * (1 + rate of interest) ^ time

```
Principal : 1000
Rate      : 10
Time      : 5

Compound interest : 1610.51
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/calculate-compound-interest/calculate_compound_interest.r` file

</details>

**Comment by Preetraj2002** [comment]
!assign
