### ISSUE TITLE
Write a Scala program to check alphabet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1204]
### Description

Write a Scala program to check alphabet

Check that the given character is an alphabet or not (a-z, A-Z).

```
Input  : a
Output : Alphabet
```
<details>
<summary>How to contribute</summary>

- Save the solution in `checkAlphabet.scala` file
- Add `checkAlphabet.scala` file in `check-alphabet` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)
