### ISSUE TITLE
[Program]: Write a R program to find cube of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#122]
### Description

Write a R program to find cube of a number

```
Input  : 2
Output : 8
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-cube-of-a-number/find_cube_of_a_number.r` file

</details>

**Comment by harshraj8843** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign

**Comment by Shaileshalluri** [comment]
!assign

**Comment by phbrgnomo** [comment]
!assign
