### ISSUE TITLE
[Program]: Write a R program to check palindrome string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1222]
### Description

Write a R program to check palindrome string

Palindrome string is a string that is same when read from left to right and right to left. For example, "aba" is a palindrome string, "abc" is not.

```
Input  : abba
Output : Palindrome String
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/check-palindrome-string/check_palindrome_string.r` file

</details>

**Comment by thecomputerfella** [comment]
!assign
