### ISSUE TITLE
[Program]: Write a R program to find perimeter of a rectangle

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1369]
### Description

Write a R program to find perimeter of a rectangle

Perimeter of rectangle = 2 × (`Length` + `Width`)

```
Length : 2
Width  : 3

Perimeter : 10
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-perimeter-of-a-rectangle/find_perimeter_of_a_rectangle.r` file

</details>

**Comment by Preetraj2002** [comment]
!assign
