### ISSUE TITLE
Write a Python program to find negative of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1431]
### Description

Write a Python program to find negative of a number

```
Input  : 5
Output : -5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-negative-of-a-number.py` file
- Add `find-negative-of-a-number.py` file in `find-negative-of-a-number` folder

</details>

**Comment by oyetanishq** [comment]
Please assign it to me.!

**Comment by BiscuitCandy** [comment]
!assign
