### ISSUE TITLE
Write a TypeScript program to print fibonacci series without recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1606]
### Description

Write a TypeScript program to print fibonacci series without recursion

```
Input  : 5
Output : 0 1 1 2 3
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintFibonacciSeriesWithoutRecursion.ts` file
- Add `PrintFibonacciSeriesWithoutRecursion.ts` file in `print-fibonacci-series-without-recursion` folder

</details>

**Comment by greeshma-d** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Greeshma-frontier,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Ariel201711** [comment]
!assign
