### ISSUE TITLE
find-fibonacci-sequence-with-iteration

### ISSUE THREAD

**Issue by icanhaskick** [codinasion-archive/codinasion-monorepo#1607]
### Description

a program to find the fibonacci sequence with a loop

**Comment by UstitvaG** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
codinasion/codinasion#1586

---

Fibonacci series without recursion is done by iteration

---

Thanks for contributing 👍🏻
