### ISSUE TITLE
Write a C++ program to find sum of numbers

### ISSUE THREAD

**Issue by icanhaskick** [codinasion-archive/codinasion-monorepo#1610]
### Description

A C++ program to find sum of numbers

```bash
Input: 1 2 3 4 5
Output: 15
```

**Comment by oyetanishq** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @tanishq-singh-2301, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by oyetanishq** [comment]
so how to contribute in this?

**Comment by oyetanishq** [comment]
can i work on this? @harshraj8843

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Issue codinasion/codinasion#759 has already been created

---

Please check the program list before submitting the new program

https://github.com/codinasion/program/blob/master/data/programs.json
