### ISSUE TITLE
[Program]: Write a C# program to find the cofactor of a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1725]
### Description

Write a C# program to find the cofactor of a matrix

The cofactor of an element a<sub>ij</sub> of a square matrix A is the determinant of the minor of A obtained by deleting the ith row and jth column of A. The cofactor of a matrix A is the matrix of cofactors of A.

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
[[-3, 6, -3], [6, -12, 6], [-3, 6, -3]]
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-the-cofactor-of-a-matrix/program/FindTheCofactorOfAMatrix.cs` file

</details>

**Comment by miguelangel31** [comment]
Hi, I was looking to make my first open source contribution. I will work on Write a C# program to find the cofactor of a matrix.

**Comment by harshraj8843** [comment]
Hey @miguelangel31 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by miguelangel31** [comment]
Ok, thanks @harshraj8843 !

**Comment by miguelangel31** [comment]
!assign
