### ISSUE TITLE
Write a Java program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1752]
### Description

Write a Java program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertCentimetersToFeet.java` file
- Add `ConvertCentimetersToFeet.java` file in `convert-centimeters-to-feet` folder

</details>

**Comment by Kunj125** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Kunj125,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Shalevro2** [comment]
!assign
