### ISSUE TITLE
[Program]: Write a Perl program to convert centimeters to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1756]
### Description

Write a Perl program to convert centimeters to feet

1 foot = 30.48 centimeters

```
Input  : 152.4
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-centimeters-to-feet/program/convert_centimeters_to_feet.pl` file

</details>

**Comment by esivakumar18** [comment]
!assign
