### ISSUE TITLE
[Program]: Write a C# program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1809]
### Description

Write a C# program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-kebabcase/program/ConvertStringToKebabcase.cs` file

</details>

**Comment by rsitters** [comment]
!assign
