### ISSUE TITLE
Write a Julia program to convert string to kebabcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1817]
### Description

Write a Julia program to convert string to kebabcase

Kebabcase is a style of writing in which all letters are lowercase and spaces are replaced with hyphens.

```
Input  : "hello world"
Output : "hello-world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-kebabcase.jl` file
- Add `convert-string-to-kebabcase.jl` file in `convert-string-to-kebabcase` folder

</details>

**Comment by RiteshK-611** [comment]
!assign
