### ISSUE TITLE
Write a C# program to convert string to titlecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1852]
### Description

Write a C# program to convert string to titlecase

Titlecase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "Hello World"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToTitlecase.cs` file
- Add `ConvertStringToTitlecase.cs` file in `convert-string-to-titlecase` folder

</details>

**Comment by royninja** [comment]
!assign this
