### ISSUE TITLE
[Program]: Write a C# program to split string into array of characters

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1876]
### Description

Write a C# program to split string into array of characters

```
Input  : "hello world"
Output : ["h", "e", "l", "l", "o", " ", "w", "o", "r", "l", "d"]
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/split-string-into-array-of-characters/program/SplitStringIntoArrayOfCharacters.cs` file

</details>

**Comment by NimrodBZB** [comment]
!assign
