### ISSUE TITLE
[Program]: Write a GO program to print number to words

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#1945]
### Description

Write a GO program to print number to words

```
Input  : 123456789
Output : One Hundred Twenty Three Million Four Hundred Fifty Six Thousand Seven Hundred Eighty Nine
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-number-to-words/program/print_number_to_words.go` file

</details>

**Comment by apurvagandhi** [comment]
!assign

**Comment by AshitaSingamsetty** [comment]
!assign
