### ISSUE TITLE
Write a Java program to convert string to lowercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2010]
### Description

Write a Java program to convert string to lowercase

```
Input  : "Hello World"
Output : "hello world"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToLowercase.java` file
- Add `ConvertStringToLowercase.java` file in `convert-string-to-lowercase` folder

</details>

**Comment by binayshaw7777** [comment]
I would like to work on this issue!

**Comment by Mikasa-Ackerman2074** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Mikasa-Ackerman2074,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by ofirtzabari** [comment]
!assign
