### ISSUE TITLE
Write a JavaScript program to find volume of a cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2074]
### Description

Write a JavaScript program to find volume of a cube

Volume of cube = `Side`^3

```
Side : 2

Volume : 8
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindVolumeOfACube.js` file
- Add `FindVolumeOfACube.js` file in `find-volume-of-a-cube` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by avireni** [comment]
!assign

**Comment by avireni** [comment]
Is this a duplicate of [find-volume-of-cube](https://github.com/codinasion/program/tree/master/program/find-volume-of-cube) ?
If yes, can i work on removing this duplicate.

**Comment by harshraj8843** [comment]
Duplicate of codinasion/codinasion#47
