### ISSUE TITLE
Write a Python program to check digit

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2164]
### Description

Write a Python program to check digit

Check wether given character is a digit (0-9).

```
Input  : 1
Output : Digit
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/check-digit.py` file
- Add `check-digit.py` file in `check-digit` folder

</details>

**Comment by Tyrell04** [comment]
!assign

**Comment by joao-vitor-souza** [comment]
Already merged by codinasion/program#3140
