### ISSUE TITLE
Write a TypeScript program to convert minutes to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2591]
### Description

Write a TypeScript program to convert minutes to hours

1 hour = 60 minutes

```
Input  : 300
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertMinutesToHours.ts` file
- Add `ConvertMinutesToHours.ts` file in `convert-minutes-to-hours` folder

</details>

**Comment by CodingWithHardik** [comment]
!assign

**Comment by oyetanishq** [comment]
!assign
