### ISSUE TITLE
[Program]: Write a Scala program to convert string to uppercase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2610]
### Description

Write a Scala program to convert string to uppercase

```
Input  : "Hello World"
Output : "HELLO WORLD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-uppercase/program/convertStringToUppercase.scala` file

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by rakibul-islam-raju** [comment]
!assign
