### ISSUE TITLE
Write a JavaScript program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2622]
### Description

Write a JavaScript program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/FindSecondLargestNumberInAnArray.js` file
- Add `FindSecondLargestNumberInAnArray.js` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by Mudi-Igbinoba** [comment]
!assign
