### ISSUE TITLE
Write a Python program to find second largest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2627]
### Description

Write a Python program to find second largest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 4
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/find-second-largest-number-in-an-array.py` file
- Add `find-second-largest-number-in-an-array.py` file in `find-second-largest-number-in-an-array` folder

</details>

**Comment by HeYPoonam** [comment]
!assign
