### ISSUE TITLE
Write a C program to convert seconds to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2678]
### Description

Write a C program to convert seconds to days

1 day = 24 hours = 1440 minutes = 86400 seconds

```
Input  : 432000
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertSecondsToDays.c` file
- Add `ConvertSecondsToDays.c` file in `convert-seconds-to-days` folder

</details>

**Comment by UstitvaG** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @astitva0011 

A PR has already been merged for this issue

Sorry for the inconvenience
