### ISSUE TITLE
[Program]: Write a R program to convert meters to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#272]
### Description

Write a R program to convert meters to miles

1 mile = 1609 meters

```
Input  : 8046.72
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-meters-to-miles/convert_meters_to_miles.r` file

</details>

**Comment by Shaileshalluri** [comment]
!assign

**Comment by Shaileshalluri** [comment]
Hi, @harshraj8843, I have issued a PR for this issue https://github.com/codinasion/codinasion/pull/4746.  Could you please review it. Thanks.
