### ISSUE TITLE
[Program]: Write a R program to find smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2924]
### Description

Write a R program to find smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-number-in-an-array/program/find_smallest_number_in_an_array.r` file

</details>

**Comment by vinodr03** [comment]
!assign
