### ISSUE TITLE
Write a C program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2931]
### Description

Write a C program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToConstantcase.c` file
- Add `ConvertStringToConstantcase.c` file in `convert-string-to-constantcase` folder

</details>

**Comment by kituuu** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @kituuu,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign

**Comment by AdityaNarayanPradhan** [comment]
!assign
