### ISSUE TITLE
[Program]: Write a C# program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2932]
### Description

Write a C# program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-constantcase/program/ConvertStringToConstantcase.cs` file

</details>

**Comment by NimrodBZB** [comment]
!assign
