### ISSUE TITLE
[Program]: Write a Swift program to convert string to constantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2949]
### Description

Write a Swift program to convert string to constantcase

Constantcase is a style of writing in which all letters are uppercase and spaces are replaced with underscores.

```
Input  : "hello world"
Output : "HELLO_WORLD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-constantcase/program/ConvertStringToConstantcase.swift` file

</details>

**Comment by ShounaKulkarni** [comment]
!assign

**Comment by ShounaKulkarni** [comment]
Hi, This is for my college project.

**Comment by ShounaKulkarni** [comment]
Please review and accept my PR: #4859 
resolved-issue-#2949-Write a Swift program to convert string to constantcase #4859
