### ISSUE TITLE
[Program]: Write a Perl program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2984]
### Description

Write a Perl program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-kilometers-to-miles/program/convert_kilometers_to_miles.pl` file

</details>

**Comment by esivakumar18** [comment]
!assign
