### ISSUE TITLE
[Program]: Write a Rust program to convert kilometers to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#2989]
### Description

Write a Rust program to convert kilometers to miles

1 mile = 1.609 kilometers

```
Input  : 8.04672
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-kilometers-to-miles/program/convert_kilometers_to_miles.rs` file

</details>

**Comment by charan-hash** [comment]
!assign
