### ISSUE TITLE
[Program]: Write a Dart program to swap two numbers without using third variable

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3018]
### Description

Write a Dart program to swap two numbers without using third variable

```
Input  : 10 20
Output : 20 10
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/swap-two-numbers-without-using-third-variable/program/swap_two_numbers_without_using_third_variable.dart` file

</details>

**Comment by abhisek-1221** [comment]
!assign

**Comment by abhisek-1221** [comment]
linked to PR codinasion/program#7197

**Comment by harshraj8843** [comment]
Closed by https://github.com/codinasion/program/pull/7197
