### ISSUE TITLE
[Program]: Write a R program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3050]
### Description

Write a R program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-pascalcase/program/convert_string_to_pascalcase.r` file

</details>

**Comment by ApurvaR1** [comment]
!assign
