### ISSUE TITLE
[Program]: Write a Swift program to convert string to pascalcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3054]
### Description

Write a Swift program to convert string to pascalcase

Pascalcase is a style of writing in which the first letter of each word is capitalized.

```
Input  : "hello world"
Output : "HelloWorld"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-pascalcase/program/ConvertStringToPascalcase.swift` file

</details>

**Comment by charan-hash** [comment]
!assign
