### ISSUE TITLE
[Program]: Write a Scala program to print pattern 1

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3074]
### Description

Write a Scala program to print pattern 1

```
Input  : 5

Output :
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5
```

<sub>Contributed by - @PraaneshSelvaraj</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-pattern-1/program/printPattern1.scala` file

</details>

**Comment by charan-hash** [comment]
!assign
