### ISSUE TITLE
[Program]: Write a Rust program to convert seconds to minutes

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#314]
### Description

Write a Rust program to convert seconds to minutes

1 minute = 60 seconds

```
Input  : 300
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-seconds-to-minutes/convert_seconds_to_minutes.rs` file

</details>

**Comment by RiteshK-611** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey bot !assign me
