### ISSUE TITLE
[Program]: Write a Rust program to find cube root of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3157]
### Description

Write a Rust program to find cube root of a number

```
Input  : 27
Output : 3
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-cube-root-of-a-number/program/find_cube_root_of_a_number.rs` file

</details>

**Comment by VRtheKing** [comment]
!assign
