### ISSUE TITLE
[Program]: Write a Dart program to convert days to hours

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3186]
### Description

Write a Dart program to convert days to hours

1 day = 24 hours

```
Input  : 5
Output : 120
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-days-to-hours/program/convert_days_to_hours.dart` file

</details>

**Comment by rsitters** [comment]
!assign
