### ISSUE TITLE
[Program]: Write a Haskell program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3210]
### Description

Write a Haskell program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/convert_time_from_24-hour_to_12-hour_format.hs` file

</details>

**Comment by lookwhoshere99** [comment]
!assign
