### ISSUE TITLE
[Program]: Write a Kotlin program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3214]
### Description

Write a Kotlin program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/ConvertTimeFrom24-hourTo12-hourFormat.kt` file

</details>

**Comment by gsquareg2** [comment]
!assign

**Comment by rsitters** [comment]
!assign
