### ISSUE TITLE
[Program]: Write a Rust program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3220]
### Description

Write a Rust program that takes a string representing a time in 24-hour format (HH:MM:SS) and converts it to 12-hour format (HH:MM:SSAM/PM). The program should handle invalid inputs and edge cases gracefully.

### Examples/Test Cases:

- **Example 1:**
  - Input: `"12:05:45"`
  - Output: `"12:05:45PM"`
  - Description: The program should accurately convert a valid 24-hour time to the 12-hour format.

- **Example 2:**
  - Input: `"00:15:30"`
  - Output: `"12:15:30AM"`
  - Description: The program should handle midnight correctly and display "AM" appropriately.

- **Example 3:**
  - Input: `"18:45:12"`
  - Output: `"06:45:12PM"`
  - Description: The program should convert an evening time to the 12-hour format.

- **Example 4:**
  - Input: `"25:10:05"`
  - Output: `"Invalid input"`
  - Description: The program should detect an invalid hour and display an error message.

- **Example 5:**
  - Input: `"09:60:00"`
  - Output: `"Invalid input"`
  - Description: The program should detect an invalid minute and display an error message.

- **Example 6:**
  - Input: `"abc"`
  - Output: `"Invalid input"`
  - Description: The program should handle non-numeric inputs and display an error message.

Contributors attempting to address this issue should focus on implementing these functionalities and thoroughly testing the program with these test cases.

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/convert_time_from_24-hour_to_12-hour_format.rs` file

</details>
            

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/convert_time_from_24-hour_to_12-hour_format.rs` file

</details>

**Comment by SaideepKondur** [comment]
!assign
