### ISSUE TITLE
[Program]: Write a Swift program to convert time from 24-hour to 12-hour format

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3222]
### Description

Write a Swift program to convert time from 24-hour to 12-hour format

```
Input  : 12:05:45
Output : 12:05:45PM
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-time-from-24-hour-to-12-hour-format/program/ConvertTimeFrom24-hourTo12-hourFormat.swift` file

</details>

**Comment by LeventCelik** [comment]
!assign
