### ISSUE TITLE
[Program]: Write a R program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3260]
### Description

Write a R program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/check-lower-case/program/check_lower_case.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by lingalaviran** [comment]
!assign
