### ISSUE TITLE
Write a Ruby program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3261]
### Description

Write a Ruby program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckLowerCase.rb` file
- Add `CheckLowerCase.rb` file in `check-lower-case` folder

</details>

**Comment by PraaneshSelvaraj** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @PraaneshSelvaraj,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by jfinley6** [comment]
!assign
