### ISSUE TITLE
[Program]: Write a Rust program to check lower case

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3262]
### Description

Write a Rust program to check lower case

Check if given character is lower case (a-z).

```
Input  : a
Output : Lower Case
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/check-lower-case/program/check_lower_case.rs` file

</details>

**Comment by james-tharit** [comment]
!assign
