### ISSUE TITLE
Write a Java program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3316]
### Description

Write a Java program to convert a string to an integer

```
Input  : "123"
Output : 123
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertAStringToAnInteger.java` file
- Add `ConvertAStringToAnInteger.java` file in `convert-a-string-to-an-integer` folder

</details>

**Comment by brundabharadwaj** [comment]
!assign
