### ISSUE TITLE
[Program]: Write a R program to convert feet to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#332]
### Description

Write a R program to convert feet to miles

1 mile = 5280 feet

```
Input  : 26400
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-feet-to-miles/convert_feet_to_miles.r` file

</details>

**Comment by Preetraj2002** [comment]
Please assign me this task @harshraj8843

**Comment by Preetraj2002** [comment]
!assign

**Comment by Lasterminator** [comment]
!assign
