### ISSUE TITLE
[Program]: Write a R program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3323]
### Description

Write a R program to convert a string to an integer

```
Input  : "123"
Output : 123
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-a-string-to-an-integer/program/convert_a_string_to_an_integer.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by ShounaKulkarni** [comment]
Hi please review my PR - #4825
