### ISSUE TITLE
[Program]: Write a Rust program to convert a string to an integer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3325]
### Description

Write a Rust program to convert a string to an integer

```
Input  : "123"
Output : 123
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-a-string-to-an-integer/program/convert_a_string_to_an_integer.rs` file

</details>

**Comment by vedantpople4** [comment]
!assign
