### ISSUE TITLE
[Program]: Write a Scala program to print numbers from n to 1 without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3347]
### Description

Write a Scala program to print numbers from n to 1 without using a loop

```
Input  : 5
Output : 5 4 3 2 1
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-n-to-1-without-using-a-loop/program/printNumbersFromNTo1WithoutUsingALoop.scala` file

</details>

**Comment by Shubham-2110** [comment]
!assign

**Comment by Shubham-2110** [comment]
-->

## 📑 Description



## 🐞 Related Issue



Closes #3329 

@harshraj8843 Please check my PR.
Thank You!

**Comment by Shubham-2110** [comment]
-->

## 📑 Description



## 🐞 Related Issue



Closes: #3329 

@harshraj8843 Please review my PR- #4834 
Thank You!
