### ISSUE TITLE
[Program]: Write a Dart program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3375]
### Description

Write a Dart program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-second-smallest-number-in-an-array/program/find_second_smallest_number_in_an_array.dart` file

</details>

**Comment by sharvil1205** [comment]
Please assign this issue to me
!assign

**Comment by sharvil1205** [comment]
hi, looks like this issue is solved already

**Comment by harshraj8843** [comment]
Thanks @sharvil1205 for noticing 👍🏻
