### ISSUE TITLE
[Program]: Write a R program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3386]
### Description

Write a R program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-second-smallest-number-in-an-array/program/find_second_smallest_number_in_an_array.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by Preetiraj3697** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Preetiraj3697, this issue is already assigned to @Preetiraj3697 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by sushanth-0** [comment]
!assign
