### ISSUE TITLE
[Program]: Write a Swift program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3390]
### Description

Write a Swift program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-second-smallest-number-in-an-array/program/FindSecondSmallestNumberInAnArray.swift` file

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by LeventCelik** [comment]
!assign
