### ISSUE TITLE
[Program]: Write a TypeScript program to find second smallest number in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3391]
### Description

Write a TypeScript program to find second smallest number in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 2
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-second-smallest-number-in-an-array/program/FindSecondSmallestNumberInAnArray.ts` file

</details>

**Comment by jgerstbe** [comment]
!assign

**Comment by orimiles5** [comment]
!assign

**Comment by abhishekkumar35** [comment]
!assign

**Comment by abhishekkumar35** [comment]
CLOSE THIS ISSUE, ITS ALREADY SOLVED!

**Comment by harshraj8843** [comment]
Hey @abhishekkumar35 

Thanks for reporting this 👍🏻 

<sub>File Link: https://github.com/codinasion/codinasion/blob/master/program/program/find-second-smallest-number-in-an-array/FindSecondSmallestNumberInAnArray.ts</sub>
