### ISSUE TITLE
Write a Java program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3421]
### Description

Write a Java program to check integer or float

```
Input  : 1
Output : Integer
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/CheckIntegerOrFloat.java` file
- Add `CheckIntegerOrFloat.java` file in `check-integer-or-float` folder

</details>

**Comment by sauravraj188** [comment]
!assign
