### ISSUE TITLE
[Program]: Write a Swift program to check integer or float

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3432]
### Description

Write a Swift program to check integer or float

```
Input  : 1
Output : Integer
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/check-integer-or-float/program/CheckIntegerOrFloat.swift` file

</details>

**Comment by sauravraj188** [comment]
I am interested in this work
Please assign it to me

**Comment by sahanasurapureddy** [comment]
!assign
