### ISSUE TITLE
Write a JavaScript program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3547]
### Description

Write a JavaScript program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```
<details>
<summary>How to contribute</summary>

- Save the solution in `program/PrintDiamondPattern.js` file
- Add `PrintDiamondPattern.js` file in `print-diamond-pattern` folder

</details>

**Comment by greeshma-d** [comment]
!assign

**Comment by simranrangari** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @simranrangari, this issue is already assigned to @Greeshma-frontier !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by anandfresh** [comment]
!assign
