### ISSUE TITLE
[Program]: Write a Julia program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3548]
### Description

Write a Julia program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-diamond-pattern/program/print-diamond-pattern.jl` file

</details>

**Comment by charan-hash** [comment]
!assign
