### ISSUE TITLE
[Program]: Write a Rust program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3555]
### Description

Write a Rust program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-diamond-pattern/program/print_diamond_pattern.rs` file

</details>

**Comment by imsherlocked** [comment]
!assign
