### ISSUE TITLE
[Program]: Write a Swift program to print diamond pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3557]
### Description

Write a Swift program to print diamond pattern

```
Input  : 5

Output : 
    *
   ***
  *****
 *******
*********
 *******
  *****
   ***
    *
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-diamond-pattern/program/PrintDiamondPattern.swift` file

</details>

**Comment by KrunalGupta02** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @KrunalGupta02,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by sahanasurapureddy** [comment]
!assign
