### ISSUE TITLE
Print inverted pyramid pattern

### ISSUE THREAD

**Issue by PraaneshSelvaraj** [codinasion-archive/codinasion-monorepo#3560]
### Description

```
Input   : 5

Output : 
1 2 3 4 5
1 2 3 4 
1 2 3
1 2
1
```

**Comment by bhavesh20-mb** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @bhavesh20-mb, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harshraj8843** [comment]
Program added successfully :tada:

Thanks for your contribution :hugs:
