### ISSUE TITLE
[Program]: Write a Haskell program to find the average of all numbers in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3574]
### Description

Write a Haskell program to find the average of all numbers in an array

```
Input  : [1, 2, 3, 4, 5]
Output : 3
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-the-average-of-all-numbers-in-an-array/program/find_the_average_of_all_numbers_in_an_array.hs` file

</details>

**Comment by Rohan-Kalgutkar** [comment]
!assign
