### ISSUE TITLE
Write a C++ program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3591]
### Description

Write a C++ function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "C++ Language"
    Output: "c++ lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.cpp` file
- Add `ConvertStringToVowelcase.cpp` file in `convert-string-to-vowelcase` folder

</details>

**Comment by cacti23** [comment]
!assign
