### ISSUE TITLE
[Program]: Write a Dart program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3592]
### Description

Write a Dart function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Dart Language"
    Output: "dArt lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_vowelcase.dart` file
- Add `convert_string_to_vowelcase.dart` file in `convert-string-to-vowelcase` folder

</details>

**Comment by SaideepKondur** [comment]
!assign
