### ISSUE TITLE
[Program]: Write a GO program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3594]
### Description

Write a GO function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "GO Language"
    Output: "gO lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_vowelcase.go` file
- Add `convert_string_to_vowelcase.go` file in `convert-string-to-vowelcase` folder

</details>

**Comment by apurvagandhi** [comment]
!assign
