### ISSUE TITLE
[Program]: Write a Haskell program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3595]
### Description

Write a Haskell function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Haskell Language"
    Output: "hAskEll lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert_string_to_vowelcase.hs` file
- Add `convert_string_to_vowelcase.hs` file in `convert-string-to-vowelcase` folder

</details>

**Comment by Shubham-2110** [comment]
!assign

**Comment by Shubham-2110** [comment]
## 📑 Description



## 🐞 Related Issue



Closes: #3588 

@harshraj8843 Please review my PR- #4835 
Thank You!
