### ISSUE TITLE
Write a Java program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3596]
### Description

Write a Java function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Java Language"
    Output: "jAvA lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.java` file
- Add `ConvertStringToVowelcase.java` file in `convert-string-to-vowelcase` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mail2poonam89,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by vipulkmr02** [comment]
!assign
