### ISSUE TITLE
Write a Kotlin program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3599]
### Description

Write a Kotlin function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Kotlin Language"
    Output: "kOtlIn lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.kt` file
- Add `ConvertStringToVowelcase.kt` file in `convert-string-to-vowelcase` folder

</details>

**Comment by rksp25** [comment]
!assign
