### ISSUE TITLE
Write a Python program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3602]
### Description

Write a Python function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Python Language"
    Output: "pythOn lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/convert-string-to-vowelcase.py` file
- Add `convert-string-to-vowelcase.py` file in `convert-string-to-vowelcase` folder

</details>

**Comment by EsakkiMuthu-dev** [comment]
Is this still active ?  I like to contirbute to this issue

**Comment by HadasBrave** [comment]
!assign
