### ISSUE TITLE
[Program]: Write a Swift program to convert string to vowelcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3607]
### Description

Write a Swift function that converts a given string to vowel-case. 

Vowel-case is a unique writing style where all vowels are transformed into uppercase letters and all consonants are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "hEllO wOrld"

    Input: "Programming IS Fun"
    Output: "prOgrAmmIng Is fUn"

    Input: "Swift Language"
    Output: "swIft lAngUAgE"

<details>
<summary>How to contribute</summary>

- Save the solution in `program/ConvertStringToVowelcase.swift` file
- Add `ConvertStringToVowelcase.swift` file in `convert-string-to-vowelcase` folder

</details>

**Comment by Shaileshalluri** [comment]
!assign
