### ISSUE TITLE
[Program]: Write a F# program to reverse an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3614]
### Description

Write a F# program to reverse an array

```
Input  : [1, 2, 3, 4, 5]
Output : [5, 4, 3, 2, 1]
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/reverse-an-array/ReverseAnArray.fs` file

</details>

**Comment by devbyharshit** [comment]
!assign

**Comment by devbyharshit** [comment]
@harshraj8843 I've added a MR, please have a look.
