### ISSUE TITLE
[Program]: Write a Dart program to print inverted pyramid pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3655]
### Description

Write a Dart program to print inverted pyramid pattern

```
Input   : 5

Output : 
1 2 3 4 5
1 2 3 4 
1 2 3
1 2
1
```

<sub>Contributed by - @PraaneshSelvaraj</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-inverted-pyramid-pattern/print_inverted_pyramid_pattern.dart` file

</details>

**Comment by Shubham-2110** [comment]
!assign

**Comment by jcmlumacad1** [comment]
!assign
