### ISSUE TITLE
Write a Java program to print inverted pyramid pattern

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3659]
### Description

Write a Java program to print inverted pyramid pattern

```
Input   : 5

Output : 
1 2 3 4 5
1 2 3 4 
1 2 3
1 2
1
```

<sub>Contributed by - @PraaneshSelvaraj</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintInvertedPyramidPattern.java` file
- Add `PrintInvertedPyramidPattern.java` file in `program/print-inverted-pyramid-pattern` folder

</details>

**Comment by mail2poonam89** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @mail2poonam89,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by txsnxm** [comment]
!assign
