### ISSUE TITLE
[Program]: Write a Rust program to convert fahrenheit to celsius

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3689]
### Description

Write a Rust program to convert fahrenheit to celsius

celcius = (fahrenheit - 32) * 5/9

```
Input ( F )  : -40
Output ( C ) : -40
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-fahrenheit-to-celsius/convert_fahrenheit_to_celsius.rs` file

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by kenroulier** [comment]
!assign
