### ISSUE TITLE
[Program]: Write a F# program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3740]
### Description

Write a F# program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n-without-using-a-loop/PrintNumbersFrom1ToNWithoutUsingALoop.fs` file

</details>

**Comment by namrata18s** [comment]
!assign
