### ISSUE TITLE
[Program]: Write a Julia program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3745]
### Description

Write a Julia program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n-without-using-a-loop/print-numbers-from-1-to-n-without-using-a-loop.jl` file

</details>

**Comment by AnjanaSriram** [comment]
Hey I would like to work on this

**Comment by harshraj8843** [comment]
Hey @AnjanaSriram 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by shaurya-clemson** [comment]
!assign
