### ISSUE TITLE
[Program]: Write a Scala program to print numbers from 1 to n without using a loop

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3753]
### Description

Write a Scala program to print numbers from 1 to n without using a loop

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n-without-using-a-loop/printNumbersFrom1ToNWithoutUsingALoop.scala` file

</details>

**Comment by 1movemate** [comment]
!assign

**Comment by sahanasurapureddy** [comment]
!assign
