### ISSUE TITLE
[Program]: Find power of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3756]
### Description

Write a program to find power of a number

Power of a number is the result of multiplying a number by itself a certain number of times. For example, 2^3 = 2 * 2 * 2 = 8. The number 2 is the base and 3 is the exponent.

```
Input  : 2 3
Output : 8
```

### Tracking Issues

- [x] codinasion/codinasion#3757
- [x] codinasion/codinasion#3758
- [x] codinasion/codinasion#3759
- [x] codinasion/codinasion#3760
- [x] codinasion/codinasion#3761
- [x] codinasion/codinasion#3762
- [x] codinasion/codinasion#3763
- [x] codinasion/codinasion#3764
- [x] codinasion/codinasion#3765
- [x] codinasion/codinasion#3766
- [x] codinasion/codinasion#3767
- [x] codinasion/codinasion#3768
- [x] codinasion/codinasion#3769
- [x] codinasion/codinasion#3770
- [x] codinasion/codinasion#3771
- [x] codinasion/codinasion#3772
- [x] codinasion/codinasion#3773
- [x] codinasion/codinasion#3774
- [x] codinasion/codinasion#3775
- [x] codinasion/codinasion#3776

**Comment by hugosmoreira** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @hugosmoreira, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.
