### ISSUE TITLE
[Program]: Write a F# program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3783]
### Description

Write a F# program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-element-in-a-matrix/FindSmallestElementInAMatrix.fs` file

</details>

**Comment by anejman** [comment]
!assign
