### ISSUE TITLE
[Program]: Write a Haskell program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3785]
### Description

Write a Haskell program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-element-in-a-matrix/find_smallest_element_in_a_matrix.hs` file

</details>

**Comment by Shubham-2110** [comment]
!assign

**Comment by sricharan200** [comment]
!assign
