### ISSUE TITLE
[Program]: Write a Julia program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3788]
### Description

Write a Julia program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-element-in-a-matrix/find-smallest-element-in-a-matrix.jl` file

</details>

**Comment by Shubham-2110** [comment]
!assign

**Comment by Shubham-2110** [comment]
## 📑 Description



## 🐞 Related Issue



Closes: #3778 

@harshraj8843 Please review my PR- #4836 
Thank You!
