### ISSUE TITLE
[Program]: Write a R program to find smallest element in a matrix

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3793]
### Description

Write a R program to find smallest element in a matrix

```
Input :
4 7 3
9 4 2
0 6 4

Output : 0
```

<sub>Contributed by - @ShubhraSuman</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-smallest-element-in-a-matrix/find_smallest_element_in_a_matrix.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by sushanth-0** [comment]
!assign

**Comment by harshraj8843** [comment]
Sorry @sushanth-0 

#4761 already linked to this issue
