### ISSUE TITLE
[Program]: Write a Haskell program to convert string to consonantcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3806]
### Description

Write a Haskell function that converts a given string to consonant-case. 

Consonant-case is a unique writing style where all Consonant are transformed into uppercase letters and all Vowel are converted into lowercase letters.

### Example

    Input: "hello world"
    Output: "HeLLo WoRLD"

    Input: "Programming IS Fun"
    Output: "PRoGRaMMiNG iS FuN"

    Input: "Programming Language"
    Output: "PRoGRaMMiNG LaNGuaGe"

<details>
<summary>How to contribute</summary>

- Save the solution in `convert_string_to_consonantcase.hs` file
- Add `convert_string_to_consonantcase.hs` file in `program/convert-string-to-consonantcase` folder

</details>

**Comment by charan-hash** [comment]
!assign
