### ISSUE TITLE
[Program]: Convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3820]
### Description

Write a program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

```
Input  : "hello world"
Output : "HELLO WORLD"
```

### Tracking Issues

- [x] codinasion/codinasion#3821
- [x] codinasion/codinasion#3822
- [x] codinasion/codinasion#3823
- [x] codinasion/codinasion#3824
- [x] codinasion/codinasion#3825
- [x] codinasion/codinasion#3826
- [x] codinasion/codinasion#3827
- [x] codinasion/codinasion#3828
- [x] codinasion/codinasion#3829
- [x] codinasion/codinasion#3830
- [x] codinasion/codinasion#3831
- [x] codinasion/codinasion#3832
- [x] codinasion/codinasion#3833
- [x] codinasion/codinasion#3834
- [x] codinasion/codinasion#3835
- [x] codinasion/codinasion#3836
- [x] codinasion/codinasion#3837
- [x] codinasion/codinasion#3838
- [x] codinasion/codinasion#3839
- [x] codinasion/codinasion#3840

**Comment by Sankalps-world** [comment]
#include <iostream>
#include <string>

std::string reverseCase(const std::string& str) {
    std::string result = str;
    for (char& c : result) {
        if (std::islower(c)) {
            c = std::toupper(c);
        } else if (std::isupper(c)) {
            c = std::tolower(c);
        }
    }
    return result;
}

int main() {
    std::string inputString;
    std::cout << "Enter a string: ";
    std::getline(std::cin, inputString);

    std::string reversedCaseString = reverseCase(inputString);

    std::cout << "String in reverse case: " << reversedCaseString << std::endl;

    return 0;
}
