### ISSUE TITLE
[Program]: Write a F# program to convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3825]
### Description

Write a F# program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

```
Input  : "hello world"
Output : "HELLO WORLD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-reversecase/ConvertStringToReversecase.fs` file

</details>

**Comment by devbyharshit** [comment]
!assign

**Comment by devbyharshit** [comment]
@harshraj8843 
I've added a MR, please review it once you're avialable.
