### ISSUE TITLE
[Program]: Write a Perl program to convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3832]
## Description

I propose the addition of a Perl program that converts a given string to reverse case, following the reversecase style of writing. In reversecase, all lowercase letters are converted to uppercase, and all uppercase letters are converted to lowercase.

### Examples

1. **Example:**
   - **Input:** "helLo"
   - **Output:** "HELlO"

2. **Example:**
   - **Input:** "ReVeRsEcAsE"
   - **Output:** "rEvErSeCaSe"

3. **Example:**
   - **Input:** "123!@#"
   - **Output:** "123!@#"

## Acceptance Criteria

- The program should be implemented in Perl.
- It should handle various input cases, including empty strings and strings with special characters.
- The output should be a new string where the case of each letter is reversed.
- The code should be well-documented with comments explaining the logic.
- Unit tests should be provided to ensure the correctness of the implementation.

## Additional Information

- If any external libraries or dependencies are required, please specify them.
- If there are any potential challenges or considerations in implementing this feature, please outline them.

## Related Files

- The Perl program file (e.g., `ReverseCaseConverter.pl`).
- Unit test files (e.g., `ReverseCaseConverterTest.pl`).

## Note

Before submitting the pull request, ensure that the code follows our coding standards and conventions.

Feel free to discuss any aspects of this feature request in the comments. Thank you!

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-reversecase/convert_string_to_reversecase.pl` file

</details>

**Comment by Rohan-Kalgutkar** [comment]
!assign
