### ISSUE TITLE
[Program]: Write a Rust program to convert string to reversecase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3837]
### Description

Write a Rust program to convert string to reversecase

Reversecase is a style of writing in which all lowercase letters are converted to uppercase and all uppercase letters are converted to lowercase.

```
Input  : "hello world"
Output : "HELLO WORLD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-reversecase/convert_string_to_reversecase.rs` file

</details>

**Comment by vedantpople4** [comment]
!assign
