### ISSUE TITLE
[Program]: Write a Julia program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3872]
### Description

Write a Julia program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n/print-numbers-from-1-to-n.jl` file

</details>

**Comment by ReprogramAkash** [comment]
!assign

**Comment by ReprogramAkash** [comment]
Hi @harshraj8843 I would like to work on this
