### ISSUE TITLE
[Program]: Write a R program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3877]
### Description

Write a R program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n/print_numbers_from_1_to_n.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by ReprogramAkash** [comment]
!assign

**Comment by ReprogramAkash** [comment]
Hi @harshraj8843 Is this issue still open?

**Comment by harshraj8843** [comment]
Yes @ReprogramAkash
