### ISSUE TITLE
[Program]: Write a Swift program to print numbers from 1 to n

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3881]
### Description

Write a Swift program to print numbers from 1 to n

```
Input  : 5
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-numbers-from-1-to-n/PrintNumbersFrom1ToN.swift` file

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by ReprogramAkash** [comment]
!assign

**Comment by ReprogramAkash** [comment]
Hi @harshraj8843 I would like to work on this.

**Comment by harshraj8843** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ReprogramAkash 

The [assign-me BOT](https://github.com/apps/assign-me) issue has been fixed

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```
