### ISSUE TITLE
[Program]: Write a Rust program to convert rupees to paise

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3900]
### Description

Write a Rust program to convert rupees to paise

```
Input  ( Rs ) : 1
Output ( Ps ) : 100
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-rupees-to-paise/convert_rupees_to_paise.rs` file

</details>

**Comment by esivakumar18** [comment]
!assign

**Comment by vedantpople4** [comment]
!assign
