### ISSUE TITLE
[Program]: Find sum of squares of numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3904]
### Description

Write a program to find sum of squares of numbers

Suppose you have a list of numbers, and you want to find the sum of the squares of those numbers. For example, if you have the list `[1, 2, 3]`, you want to find the sum of the squares of those numbers, which is `1^2 + 2^2 + 3^2 = 14`.

```
Input  : 1 2 3 4 5
Output : 55
```

### Tracking Issues

- [x] codinasion/codinasion#3905
- [x] codinasion/codinasion#3906
- [x] codinasion/codinasion#3907
- [x] codinasion/codinasion#3908
- [x] codinasion/codinasion#3909
- [x] codinasion/codinasion#3910
- [x] codinasion/codinasion#3911
- [x] codinasion/codinasion#3912
- [x] codinasion/codinasion#3913
- [x] codinasion/codinasion#3914
- [x] codinasion/codinasion#3915
- [x] codinasion/codinasion#3916
- [x] codinasion/codinasion#3917
- [x] codinasion/codinasion#3918
- [x] codinasion/codinasion#3919
- [x] codinasion/codinasion#3920
- [x] codinasion/codinasion#3921
- [x] codinasion/codinasion#3922
- [x] codinasion/codinasion#3923
- [x] codinasion/codinasion#3924

**Comment by Riyazul555** [comment]
!assign
