### ISSUE TITLE
[Program]: Calculate simple interest

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3946]
### Description

Write a program to calculate simple interest

Simple interest = (principal amount * rate of interest * time) / 100

```
Principal : 1000
Rate      : 10
Time      : 5

Simple interest : 500
```

### Tracking Issues

- [x] codinasion/codinasion#3947
- [x] codinasion/codinasion#3948
- [x] codinasion/codinasion#3949
- [x] codinasion/codinasion#3950
- [x] codinasion/codinasion#3951
- [x] codinasion/codinasion#3952
- [x] codinasion/codinasion#3953
- [x] codinasion/codinasion#3954
- [x] codinasion/codinasion#3955
- [x] codinasion/codinasion#3956
- [x] codinasion/codinasion#3957
- [x] codinasion/codinasion#3958
- [x] codinasion/codinasion#3959
- [x] codinasion/codinasion#3960
- [x] codinasion/codinasion#3961
- [x] codinasion/codinasion#3962
- [x] codinasion/codinasion#3963
- [x] codinasion/codinasion#3964
- [x] codinasion/codinasion#3965
- [x] codinasion/codinasion#3966

**Comment by Shaileshalluri** [comment]
!assign
