### ISSUE TITLE
[Program]: Write a F# program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3972]
### Description

Write a F# program to convert string to alternatingcase

Alternatingcase is a style of writing in which each letter is converted to its opposite case.

```
Input  : "hello world"
Output : "hElLo WoRlD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-alternatingcase/ConvertStringToAlternatingcase.fs` file

</details>

**Comment by SidMalladi** [comment]
Hi @harshraj8843  could you please assign this issue to me? @REVERB283 @pksX01
