### ISSUE TITLE
[Program]: Write a Kotlin program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3978]
## Description

I propose the addition of a Kotlin program to convert a given string to alternating case, where each letter is transformed to its opposite case. This style of writing ensures that the case of each letter alternates between uppercase and lowercase.

1. **Example:**
    - **Input:** "hello world"
    - **Output:** "hElLo wOrLd"

2. **Example:**
    - **Input:** "GitHub is Awesome!"
    - **Output:** "gItHuB Is aWeSoMe!"

3. **Example:**
    - **Input:** "12345 AbCdEf"
    - **Output:** "12345 aBcDeF"
## Acceptance Criteria

- The program should be implemented in Kotlin.
- It should handle various input cases, including but not limited to empty strings and strings with special characters.
- The output should be a new string where the case of each letter alternates as described.
- The code should be well-documented with comments explaining the logic.
- Unit tests should be provided to verify the correctness of the implementation.

## Additional Information

- If any external libraries or dependencies are necessary, please specify them.
- Include information on potential challenges or considerations in implementing this feature.

## Related Files

- Kotlin program file (e.g., `AlternatingCaseConverter.kt`).
- Unit test files (e.g., `AlternatingCaseConverterTest.kt`).

## Note

Before submitting the pull request, ensure that the code adheres to our coding standards and conventions.

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-alternatingcase/ConvertStringToAlternatingcase.kt` file

</details>

**Comment by gsquareg2** [comment]
!assign

**Comment by bhushanmarathe** [comment]
!assign
