### ISSUE TITLE
[Program]: Write a Scala program to convert string to alternatingcase

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3985]
### Description

Write a Scala program to convert string to alternatingcase

Alternatingcase is a style of writing in which each letter is converted to its opposite case.

```
Input  : "hello world"
Output : "hElLo WoRlD"
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-string-to-alternatingcase/convertStringToAlternatingcase.scala` file

</details>

**Comment by moaldeen** [comment]
!assign
