### ISSUE TITLE
[Program]: Find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3988]
### Description

Write a program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```

### Tracking Issues

- [x] codinasion/codinasion#3989
- [x] codinasion/codinasion#3990
- [x] codinasion/codinasion#3991
- [x] codinasion/codinasion#3992
- [x] codinasion/codinasion#3993
- [x] codinasion/codinasion#3994
- [x] codinasion/codinasion#3995
- [x] codinasion/codinasion#3996
- [x] codinasion/codinasion#3997
- [x] codinasion/codinasion#3998
- [x] codinasion/codinasion#3999
- [x] codinasion/codinasion#4000
- [x] codinasion/codinasion#4001
- [x] codinasion/codinasion#4002
- [x] codinasion/codinasion#4003
- [x] codinasion/codinasion#4004
- [x] codinasion/codinasion#4005
- [x] codinasion/codinasion#4006
- [x] codinasion/codinasion#4007
- [x] codinasion/codinasion#4008

**Comment by DeepakSuda** [comment]
can i work on this issue

**Comment by harshraj8843** [comment]
Hey @DeepakSuda 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

> **Note** This is not a `good first issue`. You can check out the issues listed above 🤗

**Comment by DeepakSuda** [comment]
ohh! ok

**Comment by DeepakSuda** [comment]
!assign

**Comment by Rohan-Kalgutkar** [comment]
!assign
