### ISSUE TITLE
[Program]: Write a F# program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3993]
### Description

Write a F# program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-n-natural-numbers-using-formula/FindSumOfNNaturalNumbersUsingFormula.fs` file

</details>

**Comment by devbyharshit** [comment]
!assign

**Comment by devbyharshit** [comment]
@harshraj8843 I've completed this issue and just wanted to raise a MR. Is there any branching strategy that you guys follow because I couldn't find that in docs?

**Comment by harshraj8843** [comment]
Hey @REVERB283 

We do not have a specific branching strategy. To make it easier, create a branch with your username 🤗

**Comment by devbyharshit** [comment]
@harshraj8843 I've created the above MR please review when you're avialable
