### ISSUE TITLE
[Program]: Write a Haskell program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3995]
### Description

Write a Haskell program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-n-natural-numbers-using-formula/find_sum_of_n_natural_numbers_using_formula.hs` file

</details>

**Comment by SidMalladi** [comment]
Hi @harshraj8843 could you please assign this issue to me?

**Comment by harshraj8843** [comment]
Hey @SidMalladi 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Shaileshalluri** [comment]
!assign
