### ISSUE TITLE
Write a Julia program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#3998]
### Description

Write a Julia program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```
<details>
<summary>How to contribute</summary>

- Save the solution in `find-sum-of-n-natural-numbers-using-formula.jl` file
- Add `find-sum-of-n-natural-numbers-using-formula.jl` file in `program/find-sum-of-n-natural-numbers-using-formula` folder

</details>

**Comment by victoriacheng15** [comment]
@champati-v need you to type `!assign` for this.

**Comment by champati-v** [comment]
!assign
