### ISSUE TITLE
[Program]: Write a R program to find sum of n natural numbers using formula

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4003]
### Description

Write a R program to find sum of n natural numbers using formula

formula: n(n+1)/2

```
Input  : 5
Output : 15
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-n-natural-numbers-using-formula/find_sum_of_n_natural_numbers_using_formula.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign
