### ISSUE TITLE
Write a C program to find average of digits of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4011]
### Description

Write a C program to find average of digits of a number by recursion

Average of digits of a number is the sum of digits of the number divided by the number of digits in the number. For example, the average of digits of 123 is 6. The sum of digits of 123 is 6 and the number of digits in 123 is 3. So, the average of digits of 123 is 6/3 = 2.

```
Input  : 123
Output : 2
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindAverageOfDigitsOfANumberByRecursion.c` file
- Add `FindAverageOfDigitsOfANumberByRecursion.c` file in `program/find-average-of-digits-of-a-number-by-recursion` folder

</details>

**Comment by vipulkmr02** [comment]
!assign

**Comment by roshan798** [comment]
Hi @harshraj8843 ,
I noticed an issue (Write a C program to find average of digits of a number by recursion codinasion/codinasion#4011) in your repository and I believe I can help resolve it. Can you please guide me on how I can contribute to fixing it?

**Comment by harshraj8843** [comment]
Hey @roshan798 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

---

**How to contribute**
- Save the solution in `FindAverageOfDigitsOfANumberByRecursion.c` file
- Add `FindAverageOfDigitsOfANumberByRecursion.c` file in `program/find-average-of-digits-of-a-number-by-recursion` folder

**Comment by roshan798** [comment]
!assign
