### ISSUE TITLE
[Program]: Write a GO program to find average of digits of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4016]
### Description

Write a GO program to find average of digits of a number by recursion

Average of digits of a number is the sum of digits of the number divided by the number of digits in the number. For example, the average of digits of 123 is 6. The sum of digits of 123 is 6 and the number of digits in 123 is 3. So, the average of digits of 123 is 6/3 = 2.

```
Input  : 123
Output : 2
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-average-of-digits-of-a-number-by-recursion/find_average_of_digits_of_a_number_by_recursion.go` file

</details>

**Comment by cacti23** [comment]
!assign

**Comment by apurvagandhi** [comment]
!assign

**Comment by apurvagandhi** [comment]
This program already exists in the project. This issue should be marked as resolved.

**Comment by harshraj8843** [comment]
Hey @apurvagandhi, thanks for reporting this 👍🏻 

If you like, you can improve the code to work with recursion https://github.com/codinasion/codinasion/blob/master/program/program/find-average-of-digits-of-a-number-by-recursion/find-average-of-digits-of-a-number-by-recursion.py

```py
def average_of_digits(n):
    if n == 0:
        return 0
    digits = [int(d) for d in str(n)]
    return sum(digits) / len(digits)


print(average_of_digits(123))
```

**Comment by AshitaSingamsetty** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign test

**Comment by harshraj8843** [comment]
!assign

**Comment by MadhuS-1605** [comment]
!assign

**Comment by MadhuS-1605** [comment]
@harshraj8843 i guess this issue has fixed.
Reference: [Link](https://github.com/codinasion/codinasion/blob/master/program/program/find-average-of-digits-of-a-number-by-recursion/find_average_of_digits_of_a_number_by_recursion.go)

**Comment by MadhuS-1605** [comment]
@harshraj8843 there's already a file available for the above issue, do i need to open a new PR for the same ?

**Comment by harshraj8843** [comment]
No, Thanks for reporting 👍🏻 

File Link: https://github.com/codinasion/codinasion/blob/master/program/program/find-average-of-digits-of-a-number-by-recursion/find_average_of_digits_of_a_number_by_recursion.go
