### ISSUE TITLE
[Program]: Write a Julia program to find sum of digits of a number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4062]
### Description

Write a Julia program to find sum of digits of a number

Suppose you have a number `n` and you want to find the sum of its digits. For example, if `n = 123`, then the sum of its digits is `1 + 2 + 3 = 6`.

```
Input  : 123
Output : 6
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-digits-of-a-number/find-sum-of-digits-of-a-number.jl` file

</details>

**Comment by swapnilmukherjee** [comment]
!assign
