### ISSUE TITLE
[Program]: Merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4073]
### Description

Write a program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```

### Tracking Issues

- [x] codinasion/codinasion#4074
- [x] codinasion/codinasion#4075
- [x] codinasion/codinasion#4076
- [x] codinasion/codinasion#4077
- [x] codinasion/codinasion#4078
- [x] codinasion/codinasion#4079
- [ ] codinasion/program#5430
- [x] codinasion/codinasion#4081
- [x] codinasion/codinasion#4082
- [x] codinasion/codinasion#4083
- [x] codinasion/codinasion#4084
- [x] codinasion/codinasion#4085
- [x] codinasion/codinasion#4086
- [x] codinasion/codinasion#4087
- [x] codinasion/codinasion#4088
- [x] codinasion/codinasion#4089
- [x] codinasion/codinasion#4090
- [x] codinasion/codinasion#4091
- [x] codinasion/codinasion#4092
- [x] codinasion/codinasion#4093

**Comment by swapnilmukherjee** [comment]
!assign
