### ISSUE TITLE
Write a Java program to merge two strings

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4081]
### Description

Write a Java program to merge two strings

```
Input  : ABC DEF
Output : ABCDEF
```
<details>
<summary>How to contribute</summary>

- Save the solution in `MergeTwoStrings.java` file
- Add `MergeTwoStrings.java` file in `program/merge-two-strings` folder

</details>

**Comment by dineshlalam15** [comment]
!assign
