### ISSUE TITLE
[Program]: Write a Ruby program to cylindrically rotate a matrix by 90 degrees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4110]
### Description

Write a Ruby program to cylindrically rotate a matrix by 90 degrees

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
7 4 1
8 5 2
9 6 3
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/cylindrically-rotate-a-matrix-by-90-degrees/CylindricallyRotateAMatrixBy90Degrees.rb` file

</details>

**Comment by mayankbhatt07141** [comment]
HI @harshraj8843, Please assign this issue to me.
Thanks.

**Comment by harshraj8843** [comment]
Hey @mayankbhatt07141 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```

**Comment by mayankbhatt07141** [comment]
!assign

**Comment by harshraj8843** [comment]
Closed by https://github.com/codinasion/program/pull/6639
