### ISSUE TITLE
[Program]: Write a Scala program to cylindrically rotate a matrix by 90 degrees

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4112]
### Description

Write a Scala program to cylindrically rotate a matrix by 90 degrees

```
Input  :
1 2 3
4 5 6
7 8 9

Output :
7 4 1
8 5 2
9 6 3
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/cylindrically-rotate-a-matrix-by-90-degrees/cylindricallyRotateAMatrixBy90Degrees.scala` file

</details>

**Comment by EniolaAdemola** [comment]
!assign

**Comment by EniolaAdemola** [comment]
What should i name the file as?

**Comment by moaldeen** [comment]
!assign
