### ISSUE TITLE
[Program]: Write a Julia program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4125]
### Description

Write a Julia program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-elements-of-an-array/print-elements-of-an-array.jl` file

</details>

**Comment by RiteshK-611** [comment]
Closing issue as it is already resolved [print-elements-of-an-array.jl](https://github.com/codinasion/codinasion/blob/master/program/program/print-elements-of-an-array/print-elements-of-an-array.jl)
