### ISSUE TITLE
[Program]: Write a R program to print elements of an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4130]
### Description

Write a R program to print elements of an array

```
Input  : [1, 2, 3, 4, 5]
Output : 1 2 3 4 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-elements-of-an-array/print_elements_of_an_array.r` file

</details>

**Comment by Preetiraj3697** [comment]
!assign

**Comment by isaabutaa** [comment]
!assign

**Comment by kirankumar284** [comment]
!assign

**Comment by pranavsilimkhan** [comment]
!assign
