### ISSUE TITLE
[Program]: Write a Scala program to find sum of squares of numbers by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#415]
### Description

Write a Scala program to find sum of squares of numbers by recursion

```
Input  : 1 2 3 4 5
Output : 55
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-sum-of-squares-of-numbers-by-recursion/findSumOfSquaresOfNumbersByRecursion.scala` file

</details>

**Comment by rakibul-islam-raju** [comment]
!assign
