### ISSUE TITLE
Write a GO program to convert weeks to days

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4164]
### Description

Write a GO program to convert weeks to days

1 week = 7 days

```
Input  : 5
Output : 35
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convert_weeks_to_days.go` file
- Add `convert_weeks_to_days.go` file in `program/convert-weeks-to-days` folder

</details>

**Comment by sahdev77** [comment]
!assign

**Comment by cacti23** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @cacti23, this issue is already assigned to @sahdev77 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by vedantpople4** [comment]
!assign
