### ISSUE TITLE
Write a C program to print reverse of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4201]
### Description

Write a C program to print reverse of a number by recursion

Reverse of a number is the number obtained by reversing the digits of the original number. For example, reverse of 123 is 321. The recursive solution is to print the last digit of the number and then call the function recursively to print the remaining digits.

```
Input  : 123
Output : 321
```
<details>
<summary>How to contribute</summary>

- Save the solution in `PrintReverseOfANumberByRecursion.c` file
- Add `PrintReverseOfANumberByRecursion.c` file in `program/print-reverse-of-a-number-by-recursion` folder

</details>

**Comment by Badboy-16** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Badboy-16,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by kavish2003** [comment]
!assign
