### ISSUE TITLE
[Program]: Write a F# program to print reverse of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4205]
### Description

Write a F# program to print reverse of a number by recursion

Reverse of a number is the number obtained by reversing the digits of the original number. For example, reverse of 123 is 321. The recursive solution is to print the last digit of the number and then call the function recursively to print the remaining digits.

```
Input  : 123
Output : 321
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.fs` file

</details>

**Comment by Preetiraj3697** [comment]
Assign me.

**Comment by adityaagnihotri1** [comment]
!assign

**Comment by ReprogramAkash** [comment]
!assign
