### ISSUE TITLE
Convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4263]
### Description

Write a program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```

### Tracking Issues

- [x] codinasion/codinasion#4264
- [x] codinasion/codinasion#4265
- [x] codinasion/codinasion#4266
- [x] codinasion/codinasion#4267
- [x] codinasion/codinasion#4268
- [x] codinasion/codinasion#4269
- [x] codinasion/codinasion#4270
- [x] codinasion/codinasion#4271
- [x] codinasion/codinasion#4272
- [x] codinasion/codinasion#4273
- [x] codinasion/codinasion#4274
- [x] codinasion/codinasion#4275
- [x] codinasion/codinasion#4276
- [x] codinasion/codinasion#4277
- [x] codinasion/codinasion#4278
- [x] codinasion/codinasion#4279
- [x] codinasion/codinasion#4280
- [x] codinasion/codinasion#4281
- [x] codinasion/codinasion#4282
- [x] codinasion/codinasion#4283

**Comment by we-kash** [comment]
#include <stdio.h>
         int main()
         {
               long double inches,feet;//to store fractional part
               printf("Enter inches: ");
               scanf("%Lf",&inches);//To take take the input from the user
               feet=inches/12;
               printf("%Lf ",feet);
               return 0;
        }

**Comment by harisdev-netizen** [comment]
Can you assign me this issue?

**Comment by harshraj8843** [comment]
Hey @harisdev-netizen 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by harisdev-netizen** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @harisdev-netizen, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by harisdev-netizen** [comment]
I mean I want to work on this issue.
