### ISSUE TITLE
Write a JavaScript program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4272]
### Description

Write a JavaScript program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertInchesToFeet.js` file
- Add `ConvertInchesToFeet.js` file in `program/convert-inches-to-feet` folder

</details>

**Comment by Sumsum1000** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Sumsum1000, this issue is already assigned to @anandfresh !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.

**Comment by anandfresh** [comment]
> !assign

@Sumsum1000  this issue has been closed already
