### ISSUE TITLE
[Program]: Write a Julia program to convert inches to feet

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4273]
### Description

Write a Julia program to convert inches to feet

1 foot = 12 inches

```
Input  : 60
Output : 5
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/convert-inches-to-feet/convert-inches-to-feet.jl` file

</details>

**Comment by Lz-01** [comment]
Hello can i have this Issue?

**Comment by harshraj8843** [comment]
Hey @Lz-01 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```

**Comment by Lz-01** [comment]
!assign

**Comment by SambitAmanta** [comment]
!assign

**Comment by ReprogramAkash** [comment]
!assign

**Comment by RiteshK-611** [comment]
Closing this issue as this program is already there [convert-inches-to-feet.jl](https://github.com/codinasion/codinasion/blob/master/program/program/convert-inches-to-feet/convert-inches-to-feet.jl)
