### ISSUE TITLE
more issues

### ISSUE THREAD

**Issue by pokharel-nishan** [codinasion-archive/codinasion-monorepo#4325]
### What would you like to share?

can you please add more java issues to this repo. 

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Hey @pokharel-nishan 

We will add more issues soon 🕐 

---

If you would like to add a program, you can create a new issue 👉🏻 https://github.com/codinasion/program/issues/new?assignees=&labels=add-program&template=submit-program.yml
