### ISSUE TITLE
Write a program to check anagram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4327]
### Description

Write a program to check the anagram string

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```txt
Input  : pan, nap
Output : Anagram Strings
```

<sub>Contributed by - @sahdev77</sub>
    

### Tracking Issues

- [x] codinasion/codinasion#4328
- [x] codinasion/codinasion#4329
- [x] codinasion/codinasion#4330
- [x] codinasion/codinasion#4331
- [x] codinasion/codinasion#4333
- [x] codinasion/codinasion#4334
- [x] codinasion/codinasion#4335
- [x] codinasion/codinasion#4336
- [x] codinasion/codinasion#4337
- [x] codinasion/codinasion#4338
- [x] codinasion/codinasion#4339
- [x] codinasion/codinasion#4340
- [x] codinasion/codinasion#4341
- [x] codinasion/codinasion#4342
- [x] codinasion/codinasion#4343
- [x] codinasion/codinasion#4344
- [x] codinasion/codinasion#4345
- [x] codinasion/codinasion#4346
- [x] codinasion/codinasion#4347
- [x] codinasion/codinasion#4348

**Comment by estelacruz** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @estelacruz, `!assign` command is only for `good first issue` !!!

Please choose another issue.

Thanks for your interest in contributing to this project.
