### ISSUE TITLE
Write a C program to check anagram string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4328]
### Description

Write a C program to check anagram string

Two strings are said to be anagrams if they make a meaningful word by rearranging or shuffling the letters of the string. In other words, we can say that two strings are anagrams if they contain the same characters but in different order.

```txt
Input  : pan, nap
Output : Anagram Strings
```

<sub>Contributed by - @sahdev77</sub>
<details>
<summary>How to contribute</summary>

- Save the solution in `WriteAProgramToCheckAnagramString.c` file
- Add `WriteAProgramToCheckAnagramString.c` file in `program/write-a-program-to-check-anagram-string` folder

</details>

**Comment by roshan798** [comment]
!assign

**Comment by ohad1s** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @ohad1s, this issue is already assigned to @roshan798 !!!
          
Please choose another issue.

Thanks for your interest in contributing to this project.
