### ISSUE TITLE
convert pound to kilogram

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4352]
### Description

Write a program to convert pound to kilogram

1 pound = 0.453592 kg

```
Input  : 1
Output : 0.453592
```

<sub>Contributed by - @Aranarora</sub>
    

### Tracking Issues

- [x] codinasion/codinasion#4353
- [x] codinasion/codinasion#4354
- [x] codinasion/codinasion#4355
- [x] codinasion/codinasion#4356
- [x] codinasion/codinasion#4357
- [x] codinasion/codinasion#4358
- [x] codinasion/codinasion#4359
- [x] codinasion/codinasion#4360
- [x] codinasion/codinasion#4361
- [x] codinasion/codinasion#4362
- [x] codinasion/codinasion#4363
- [x] codinasion/codinasion#4364
- [x] codinasion/codinasion#4365
- [x] codinasion/codinasion#4366
- [x] codinasion/codinasion#4367
- [x] codinasion/codinasion#4368
- [x] codinasion/codinasion#4369
- [x] codinasion/codinasion#4370
- [x] codinasion/codinasion#4371
- [x] codinasion/codinasion#4372

**Comment by harisdev-netizen** [comment]
Assign me this issue

**Comment by harshraj8843** [comment]
Hey @harisdev-netizen 

All issues have already been closed

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```
