### ISSUE TITLE
[Program]: Write a Rust program to find weekend days from number of years

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4390]
### Description

Write a Rust program to find weekend days from number of years

Weekend means Saturday & Sunday together. In total, we have 52 weeks in a year. So there are 52 weekends in a year. So, in normal we have 104 Weekend Days.

```
Input  : 1 
Output : 104
```

<sub>Contributed by - @Aranarora</sub>

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-weekend-days-from-number-of-years/find_weekend_days_from_number_of_years.rs` file

</details>

**Comment by estelacruz** [comment]
!assign

**Comment by brundabharadwaj** [comment]
!assign

**Comment by farhan-sayeed** [comment]
!assign

**Comment by bhushanmarathe** [comment]
!assign
