### ISSUE TITLE
Improvement: User can provide input values instead of hardcoding

### ISSUE THREAD

**Issue by brundabharadwaj** [codinasion-archive/codinasion-monorepo#4397]
Update https://github.com/codinasion/program/blob/master/program/swap-two-numbers/swapTwoNumbers.scala to accept user input
              
> Improvement: User can provide input values instead of hardcoding
> 
> Expected : Values of a and b should be given as as input from the user
> Actual : Values of a and b are hardcoded. 
>            
> File details can be found in the Closed PR.
>
> _Originally posted by @brundabharadwaj in https://github.com/codinasion/program/pull/6999#pullrequestreview-1358051570_

**Comment by Yasir761** [comment]
@brundabharadwaj Can you please elaborate on this issue?

**Comment by brundabharadwaj** [comment]
> @brundabharadwaj Can you please elaborate on this issue?

@Yasir761 , sure. I have updated the details. Pl' have a look.

**Comment by Yasir761** [comment]
I'm not much familiar with Scala but I'll try to resolve it, and make a PR.
