### ISSUE TITLE
I want to Write a Java Program for Scientific Calculator.

### ISSUE THREAD

**Issue by minhaj-313** [codinasion-archive/codinasion-monorepo#4402]

**Comment by vishalsingh2972** [comment]
@minhaj-313 could you assign this to me if it's still open?

**Comment by minhaj-313** [comment]
> @minhaj-313 could you assign this to me if it's still open?

@vishalsingh2972  Actually I am waiting for codinasion response

**Comment by harshraj8843** [comment]
Hey @minhaj-313 @vishalsingh2972 

This program can't be accepted. See 👉🏻 https://github.com/codinasion/codinasion/issues/4403

Thank you for giving your time to this project 🙏🏻
