### ISSUE TITLE
[Program]: convert fahrenheit to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4411]
### Description

Write a program to convert fahrenheit to kelvin

(1°F − 32) × 5/9 + 273.15 = 255.928K

```
Input  : 1
Output : 255.928
```

<sub>Contributed by - @KyleMcIndoe</sub>
    

### Tracking Issues

- [x] codinasion/codinasion#4412
- [x] codinasion/codinasion#4413
- [x] codinasion/codinasion#4414
- [x] codinasion/codinasion#4415
- [x] codinasion/codinasion#4416
- [x] codinasion/codinasion#4417
- [x] codinasion/codinasion#4418
- [x] codinasion/codinasion#4419
- [x] codinasion/codinasion#4420
- [x] codinasion/codinasion#4421
- [x] codinasion/codinasion#4422
- [x] codinasion/codinasion#4423
- [x] codinasion/codinasion#4424
- [x] codinasion/codinasion#4425
- [x] codinasion/codinasion#4426
- [x] codinasion/codinasion#4427
- [x] codinasion/codinasion#4428
- [x] codinasion/codinasion#4429
- [x] codinasion/codinasion#4430
- [x] codinasion/codinasion#4431

**Comment by akkshayTandon** [comment]
Hey @harshraj8843 please close this issue as all tasks are done.
