### ISSUE TITLE
Close the already merged issues

### ISSUE THREAD

**Issue by akkshayTandon** [codinasion-archive/codinasion-monorepo#4457]
I recently contributed to the project and noticed there are some issues which are merged but they are still shown as open , so they need to the closed label on them. Here are some of them:
- close issue codinasion/codinasion#109
- close issue codinasion/codinasion#1292 
- close issue codinasion/codinasion#1565 
- close issue codinasion/codinasion#2532
- close issue codinasion/codinasion#2890

**Comment by harshraj8843** [comment]
Thanks for noticing these issues 🤗 

<details>
<summary>Details</summary>

The pull request should be linked to the issue by using the keyword `Closes #ISSUE_NUMBER`

</details>

**Comment by akkshayTandon** [comment]
@harshraj8843 Can you please also close codinasion/codinasion#4219 as it was merged in pull request codinasion/program#7133 
(I will also mention this on the issue page)
