### ISSUE TITLE
Improve assignment bot logic

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4544]
The assignment bot should only assign an issue to a particular user if the user comments `!assign` or `!assign me` or `please !assign me`

https://github.com/codinasion/codinasion/blob/0fa9dad5c599f318a8d417b4987e4507afc16b66/github-bots/assign-me/src/index.ts#L8

### Reference

![Screenshot from 2023-07-19 23-54-44](https://github.com/codinasion/codinasion/assets/54644599/e7a140f8-0a34-44aa-9183-3ac426c9d275)

**Comment by ThaungThanHan** [comment]
please !assign me

**Comment by ThaungThanHan** [comment]
Testing.

**Comment by ThaungThanHan** [comment]
Check if bot assigns only when we use !assign

**Comment by ThaungThanHan** [comment]
It works as expected. What is the issue?

**Comment by harshraj8843** [comment]
It should not assign a user if a suggestion is made to another user

![Screenshot from 2023-07-19 23-54-44](https://github.com/codinasion/codinasion/assets/54644599/e7a140f8-0a34-44aa-9183-3ac426c9d275)

**Comment by ThaungThanHan** [comment]
Understood. Working on it.
