### ISSUE TITLE
Improve assignment BOT logic

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#4546]
https://github.com/codinasion/codinasion/blob/e4a4a4e10739c5a5625bff4da80de081a285f135/github-bots/assign-me/src/index.ts#L8-L12

> For now, this will work 👍🏻 
>
> But we should also consider that team members can also suggest
>
> _Originally posted by @harshraj8843 in https://github.com/codinasion/codinasion/pull/4545#discussion_r1269597123_

### Reference

- #4544

**Comment by Monika-Tiyyagura** [comment]
@harshraj8843 Hey, I am interested to contribute. Can you assign me this issue to work on?

**Comment by Monika-Tiyyagura** [comment]
!assign

**Comment by Monika-Tiyyagura** [comment]
Can you help me understand more about -  ```But we should also consider that team members can also suggest``` ? 

Any example scenario would be helpful.

**Comment by harshraj8843** [comment]
Hey @Monika-Tiyyagura 

I'm sorry, but the assign-me bot has been migrated to a different organization.

Please contribute to https://github.com/ilihub/assign-me/issues/10

---

> Can you help me understand more about - But we should also consider that team members can also suggest ?

For now [Assign Me BOT](https://github.com/marketplace/assign-me) is only checking `!assign` command by anyone. But for example, a team member or a prior contributor wants to suggest to a new contributor that

> `Please use !assign command to auto assign this issue`

then the BOt should not assign the issue to the suggested person.

---

### Proposal

A simple logic will be to check only `!assign` comment, which means that the comment should only contain `!assign` or `!assign-me` or `!assign me`
