### ISSUE TITLE
[ADD PROGRAM]: Write a program to flatten deeply nested arrays.

### ISSUE THREAD

**Issue by ghost** [codinasion-archive/codinasion-monorepo#4552]
### Description

Write A JavaScript Program To Flatten A Nested Array To The Depth n without using Array.flat() method.

```
const arr = [[1, 2, 3], [4, 5, 6], [7, 8, [9, 10, 11], 12], [13, 14, 15]];
const n = 2;
const result = flat(arr, n);
console.log(result);
// Output: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
```
Note - Program should not use any built-in method.

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/codinasion/.github/blob/master/CODE_OF_CONDUCT.md)

**Comment by akshatsharma1290** [comment]
I'll make a pull request to solve this issue.
