### ISSUE TITLE
[DOCS]: String to Sentence Case Proper Docs.

### ISSUE THREAD

**Issue by 0ME9A** [codinasion-archive/codinasion-monorepo#4581]
## Issue: 📄 Documentation issue

1. The documentation on sentence cases is unclear.
2. The rules for sentence cases are not clearly defined. Sentence case involves more than just capitalizing the first letter of the first word and making all other letters lowercase. There are exceptions, such as proper nouns and acronyms, which should always be capitalized.
3. There is a lack of examples demonstrating the correct use of sentence cases.

### Description

Write a C# program that converts a string to a sentence case.

Sentence case is a style of writing in which the first letter of the first word is capitalized, while all other letters are in lowercase. However, there are some exceptions to this rule. For example, proper nouns (such as names of people, places, organizations, etc.) and acronyms (such as NASA, FBI, etc.) should always be capitalized, regardless of their position in the sentence. The first word after a colon or a semicolon may also be capitalized.

Here is an example of a sentence in sentence case: "**The quick brown fox jumps over the lazy dog.**" In this sentence, only the first letter of the first word is capitalized, while all other letters are in lowercase. However, if the sentence contains proper nouns or acronyms, they should also be capitalized. For example: "**John and Jane went to New York to visit the Museum of Modern Art (MoMA).**" In this sentence, the first letter of the first word, as well as the proper nouns "John", "Jane", "New York", and "Museum of Modern Art", and the acronym "MoMA" are capitalized.

Here are some examples of converting strings to sentence case using a C# program:

Example 1:
```
Input: "john and jane went to new york to visit the museum of modern art (moma)"
Output: "John and Jane went to New York to visit the Museum of Modern Art (MoMA)"
```

Example 2:
```
Input: "the united nations (un) is an international organization"
Output: "The United Nations (UN) is an international organization"
```

Example 3:
```
Input: "the cat is sleeping; however, the dog is awake"
Output: "The cat is sleeping; however, the dog is awake"
```

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
You are absolutely right. But how can we identify if the word is a noun or not 🤔 ?

**Comment by 0ME9A** [comment]
We can't identify but it can be done by using constant value.

string= "john and jane went to new york to visit the museum of modern art (moma)"
constant = ["John", "Jane", "New York", "Museum of Modern Art", "(MoMA)"]

Logic steps could be:-
1. Convert string into lowerCase
2. Loop through constant if constant item matches a string word change it with const item.
3. If there is no constant just convert to lowercase and capitalize the string's 1st word 1st letter.

***or***

1. use regExp 

**Constant** can give a plus point to solve the solution but may be slow in response.

 **Note:-**  Logic may be different to solve the solution, it depends on developers thinking.

**Comment by 0ME9A** [comment]
You should update the doc and close the issue, you don't think. 🤔

**Comment by harshraj8843** [comment]
#4582
