### ISSUE TITLE
[Program]: Write a C# program to print ascii value of a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#480]
### Description

Write a C# program to print ascii value of a string

ASCII value is the numeric representation of a character. For example, the ASCII value of the character 'A' is 65. The ASCII value of the character 'a' is 97. The ASCII value of the character '0' is 48. The ASCII value of the character ' ' is 32.

```
Input  : ABC
Output : 65 66 67
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.cs` file

</details>

**Comment by g-s-eire** [comment]
Hi, I am new to open source and would like to get involved in this issue.

**Comment by harshraj8843** [comment]
Hey @g-s-eire 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by g-s-eire** [comment]
!assign
