### ISSUE TITLE
Write a C# program to reverse words in a string

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5000]
### Description

Write a C# program to reverse words in a string

```
Input  : "Hello World"
Output : "World Hello"
```

<sub>Contributed by - @Parvezkhan0</sub>
<details>
<summary>How to contribute</summary>

- Fork this repository
- Create a new branch
- Save the solution in `program/reverse-words-in-a-string/ReverseWordsInAString.cs`
- Commit the changes
- Create a pull request

</details>

**Comment by Parvezkhan0** [comment]
!assign

**Comment by harshraj8843** [comment]
This issue is linked to #5028
