### ISSUE TITLE
Write a JavaScript program to find the largest two elements in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5043]
### Description

Write a JavaScript program to find the largest two elements in an array

```text
Input: arr[] = {12, 13, 1, 10, 34, 1}
Output: The largest two elements are 34 and 13

Input: arr[] = {10, 5, 10}
Output: The largest two elements are 10 and 5

Input: arr[] = {10, 10, 10}
Output: The largest two elements are 10 and 10
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/find-the-largest-two-elements-in-an-array/FindTheLargestTwoElementsInAnArray.js`
- Commit the changes
- Create a pull request

</details>

**Comment by echelonCodes** [comment]
Hello @harshraj8843, this looks like something I can work on. Can you please assign it to me?
Thank you!
!assign

**Comment by harshraj8843** [comment]
Hey @echelonnought 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by echelonCodes** [comment]
!assign

**Comment by echelonCodes** [comment]
Perfect, thank you for that!
