### ISSUE TITLE
Write a Scala program to find the largest two elements in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5052]
### Description

Write a Scala program to find the largest two elements in an array

```text
Input: arr[] = {12, 13, 1, 10, 34, 1}
Output: The largest two elements are 34 and 13

Input: arr[] = {10, 5, 10}
Output: The largest two elements are 10 and 5

Input: arr[] = {10, 10, 10}
Output: The largest two elements are 10 and 10
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/find-the-largest-two-elements-in-an-array/findTheLargestTwoElementsInAnArray.scala`
- Commit the changes
- Create a pull request

</details>

**Comment by Riyazul555** [comment]
!assign
