### ISSUE TITLE
[Program]: Write a Dart program to find volume of cube

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#51]
### Description

Write a Dart program to find volume of cube

Volume of cube = (edge of cube)^3

```
Input  : 2
Output : 8
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-volume-of-cube/find_volume_of_cube.dart` file

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign

**Comment by harshraj8843** [comment]
!assign

**Comment by ghost** [comment]
Hey @harshraj8843, you are already assigned to this issue!

**Comment by pksX01** [comment]
!assign
