### ISSUE TITLE
Write a Java program to implement ternary search

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5117]
### Description

Write a Java program to implement ternary search

Ternary search is a divide and conquer algorithm that can be used to find an element in an array. It is similar to binary search where we divide the array into two parts but in this algorithm, we divide the given array into three parts and determine which has the key (searched element).

### Pseudocode

```text
procedure ternary_search
   A ← sorted array
   value ← value to be searched
   l ← leftmost index
   r ← rightmost index
   
   while l ≤ r do
   
      partition size = (r-l)/3
      mid1 = l + partition_size
      mid2 = r - partition_size
      
      if A[mid1] = value
         return mid1
         
      if A[mid2] = value
         return mid2
         
      if value < A[mid1]
         set r = mid1 - 1
         
      else if value > A[mid2]
         set l = mid2 + 1
         
      else
         set l = mid1 + 1
         set r = mid2 - 1
         
   end while
   
   return -1
end procedure
```

### Example

```text
list = [1,2,3,4,5]
value = 4

Output : 3
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/implement-ternary-search/ImplementTernarySearch.java`
- Commit the changes
- Create a pull request

</details>

**Comment by prathebaAT** [comment]
!assign

**Comment by sudeepkanda** [comment]
!assign

**Comment by sudeepkanda** [comment]
public class ImplementTernarySearch{
    public static void main(String [] args){
        // ternary search
        int[] arr ={1,2,3,4,5};
        int target=5;
        System.out.println(ternarySearch(arr,target,0,arr.length-1));//returns index
    } 
    static int ternarySearch(int[] arr,int target,int start,int end){
        if(target==arr[end]){
            return end;
        }
        while(start<=end){
        int div=(end-start)/3;
        
        
        if (arr[start+div]>target ){
            end=div-1;
           // return ternarySearch(arr,target,start,start+div-1);
        }
        else if(arr[start+div]==target ){
            return div;
        }
        else if (arr[end-div]>target ){
            start=div+1;
            end=end-div-1;
            //return ternarySearch(arr,target,start+div+1,end-div-1);
        }
        else if(arr[end-div]==target) return end-div;
        else{
            start=end-div+1;
            //return ternarySearch(arr,target,end-div+1,end);
        }
        
    }
    return -1;
    
}
}

**Comment by sudeepkanda** [comment]
my code is working I even tried with recursion I didn't upload here but by using the same logic you can implement it

**Comment by sudeepkanda** [comment]
i forgot to assign to myself!
