### ISSUE TITLE
Write a Julia program to move all zeroes to end of array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5144]
### Description

Write a Julia program to move all zeroes to end of array

```txt
Input  : arr[] = {1, 2, 0, 4, 3, 0, 5, 0};
Output : arr[] = {1, 2, 4, 3, 5, 0, 0, 0};

Input  : arr[] = {1, 2, 0, 0, 0, 3, 6};
Output : arr[] = {1, 2, 3, 6, 0, 0, 0};
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/move-all-zeroes-to-end-of-array/move-all-zeroes-to-end-of-array.jl`
- Commit the changes
- Create a pull request

</details>

**Comment by Riyazul555** [comment]
!assign
