### ISSUE TITLE
Write a JavaScript program to find the smallest three elements in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5232]
### Description

Write a JavaScript program to find the smallest three elements in an array

```txt
Input  : arr[] = {10, 4, 3, 50, 23, 90}
Output : 3 4 10

Input  : arr[] = {12, 13, 1, 10, 34, 1}
Output : 1 1 10
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.js`
- Commit the changes
- Create a pull request

</details>

**Comment by akshitchowdhury** [comment]
Assign it to me. I'll get ti done!

**Comment by harshraj8843** [comment]
Hey @akshitchowdhury 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by akshitchowdhury** [comment]
!assign

**Comment by akshitchowdhury** [comment]
@harshraj8843 When do you want it get done?

**Comment by dimitris1208** [comment]
!assign

**Comment by mktana** [comment]
!assign
