### ISSUE TITLE
Write a Kotlin program to find the smallest three elements in an array

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5234]
### Description

Write a Kotlin program to find the smallest three elements in an array

```txt
Input  : arr[] = {10, 4, 3, 50, 23, 90}
Output : 3 4 10

Input  : arr[] = {12, 13, 1, 10, 34, 1}
Output : 1 1 10
```
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/find-the-smallest-three-elements-in-an-array/FindTheSmallestThreeElementsInAnArray.kt`
- Commit the changes
- Create a pull request

</details>

**Comment by joenjogu** [comment]
!assign
