### ISSUE TITLE
Write a Swift program to convert standard date format to julian date and vice-versa

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5480]
### Description

Write a Swift program to convert standard date format to julian date and vice-versa

A Julian date is a way of displaying a date that combines the current year with the number of days since the beginning of the year. For example, January 1, 2007 is 2007001, and December 31, 2007 is 2007365.

The first two digits of a Julian date represent the year, and the last three digits represent the number of days since the beginning of the year. For example, 21-001 represents January 1, 2021, and 22-165 represents June 14, 2022.

### Example

```
Input  : 2023-06-10
Output : 2023160
```

<sub>Contributed by - @magar51</sub>
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/convert-standard-date-format-to-julian-date-and-vice-versa/ConvertStandardDateFormatToJulianDateAndVice-versa.swift`
- Commit the changes
- Create a pull request

</details>

**Comment by bulutg** [comment]
!assign
