### ISSUE TITLE
Write a GO program to convert temperature from celsius to kelvin

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5548]
### Description

Write a GO program to convert temperature from celsius to kelvin

```
Input  ( C ) : -40
Output ( K ) : 233.15
```

<sub>Contributed by - @magar51</sub>
<details>
<summary>How to contribute</summary>

- Comment `!assign` to assign this issue to yourself
- Fork this repository
- Create a new branch
- Save the solution in `program/program/convert-temperature-from-celsius-to-kelvin/convert_temperature_from_celsius_to_kelvin.go`
- Commit the changes
- Create a pull request

</details>

**Comment by nine03** [comment]
!assign
