### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#5641]
### Discussed in https://github.com/orgs/codinasion/discussions/5640

<div type='discussions-op-text'>

<sup>Originally posted by **harshraj8843** April 10, 2024</sup>
Hey folks 😀 

We need a new website for https://codinasion.org

Anyone interested in contributing, please discuss here 👇🏻 

## Proposal

- Next Js for Frontend

## Json Data

These files are updated regularly

- Programs Data: https://github.com/codinasion/codinasion/tree/program-data
- Contributors Data: https://github.com/codinasion/codinasion/tree/contributors-data

<details>
<summary>Good First Issue</summary>

Here is our previous logic for getting good first issues

https://github.com/codinasion/codinasion/blob/495d6bf3606237b93c543be8affdb4fc9b316728/website/src/data/good-first-issues.ts#L4-L25

https://github.com/codinasion/codinasion/blob/495d6bf3606237b93c543be8affdb4fc9b316728/website/src/data/good-first-issues.ts#L29-L65

</details>

## Reference

Previous website code: https://github.com/codinasion/codinasion/tree/495d6bf3606237b93c543be8affdb4fc9b316728/website

<sub>cc/ @codinasion/codinasion @codinasion/admin</sub></div>

**Comment by Amedi-Imbira** [comment]
I can craft one with Vue.js for the frontend. And I can upgrade the UI/UX

**Comment by HaiyingLiao** [comment]
Hey, how to contribute on this?

**Comment by isyuricunha** [comment]
> Hey, how to contribute on this?

I believe that if you have any ideas, you can share them here.

You can also use the old code (mentioned in this discussion or [here](https://github.com/codinasion/codinasion/tree/495d6bf3606237b93c543be8affdb4fc9b316728/website)) as a basis to suggest the new website.
