### ISSUE TITLE
[Program]: Write a Perl program to find maximum of n numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#569]
### Description

Write a Perl program to find maximum of n numbers

```
Input  : 10 20 30 40 50
Output : 50
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/find-maximum-of-n-numbers/find_maximum_of_n_numbers.pl` file

</details>

**Comment by esivakumar18** [comment]
!assign
