### ISSUE TITLE
Write a C program to find factorial of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#640]
### Description

Write a C program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.c` file
- Add `FindFactorialOfANumberByRecursion.c` file in `find-factorial-of-a-number-by-recursion` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by Osher160** [comment]
!assign
