### ISSUE TITLE
Write a C++ program to find factorial of a number by recursion

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#642]
### Description

Write a C++ program to find factorial of a number by recursion

Factorial of a number is the product of all the numbers from 1 to that number. For example, factorial of 5 is 5\*4\*3\*2\*1 = 120.

```
Input  : 5
Output : 120
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindFactorialOfANumberByRecursion.cpp` file
- Add `FindFactorialOfANumberByRecursion.cpp` file in `find-factorial-of-a-number-by-recursion` folder

</details>

**Comment by SRR-CODER** [comment]
!assign

**Comment by SRR-CODER** [comment]
closes codinasion/codinasion#642 codinasion/codinasion#602 codinasion/codinasion#622 codinasion/program#834 codinasion/program#838
