### ISSUE TITLE
Write a C program to convert minutes to weeks

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#800]
### Description

Write a C program to convert minutes to weeks

1 week = 7 days = 168 hours = 10080 minutes

```
Input  : 50400
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `ConvertMinutesToWeeks.c` file
- Add `ConvertMinutesToWeeks.c` file in `convert-minutes-to-weeks` folder

</details>

**Comment by anxkhn** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @anxkhn,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by pokharel-nishan** [comment]
!assign
