### ISSUE TITLE
Write a TypeScript program to find volume of a cuboid

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#87]
### Description

Write a TypeScript program to find volume of a cuboid

Volume of a cuboid = `Length` × `Width` × `Height`

```
Length : 2
Width  : 3
Height : 4

Volume : 24
```
<details>
<summary>How to contribute</summary>

- Save the solution in `FindVolumeOfACuboid.ts` file
- Add `FindVolumeOfACuboid.ts` file in `find-volume-of-a-cuboid` folder

</details>

**Comment by muhammadjufry** [comment]
!assign
