### ISSUE TITLE
Write a Scala program to convert inches to miles

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#956]
### Description

Write a Scala program to convert inches to miles

1 mile = 63360 inches

```
Input  : 316800
Output : 5
```
<details>
<summary>How to contribute</summary>

- Save the solution in `convertInchesToMiles.scala` file
- Add `convertInchesToMiles.scala` file in `convert-inches-to-miles` folder

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by esivakumar18** [comment]
!assign
