### ISSUE TITLE
[Program]: Write a GO program to check armstrong number

### ISSUE THREAD

**Issue by harshraj8843** [codinasion-archive/codinasion-monorepo#985]
### Description

Write a GO program to check armstrong number

An Armstrong number is a number that is equal to the sum of cubes of its digits.

```
Input  : 153
Output : Armstrong Number
```

<details>
<summary>How to contribute</summary>

- Save the solution in `program/program/check-armstrong-number/check_armstrong_number.go` file

</details>

**Comment by Chirag8023** [comment]
!assign

**Comment by harshraj8843** [comment]
Hey @Chirag8023,

This issue has been assigned to you for more than 15 days.

We are unassigning you from this issue.

If you are still interested in contributing to this issue, please get auto-assigned on the issue by commenting `!assign` again.

Thanks for your contributions :)

**Comment by AshitaSingamsetty** [comment]
!assign
